language: php
php:
- 5.5
- 5.6
install: composer install
script:
- ./vendor/bin/phpunit
- ./vendor/bin/phing test
after_success: ./vendor/bin/phing report-to-coveralls
notifications:
  email:
    recipients:
    - bert@2dotstwice.be
    - sander@2dotstwice.be
    - kristof@2dotstwice.be
